spring:
  application:
    name: recipe
  datasource:
    url: "jdbc:postgresql://localhost:5432/recipes"
    username: "superadmin"
    password: "@k$h!t"
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        show_sql: true

  cache:
    cache-names:
      - recipe
    type: REDIS
  data:
    redis:
      port: 6379
      host: localhost


  security:
    user:
      name: bunnu
      password: R@d#!k@ $hArm@

logging:
  level:
    root: info

server:
  port: 8085



data-source:
  base-url: https://dummyjson.com/recipe

