spring:
  application:
    name: recipe
  datasource:
    url: "jdbc:postgresql://localhost:5432/recipes"
    username: ${USER_NAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: "update"
    properties:
      hibernate:
        show_sql: true

  cache:
    cache-names:
      - recipe
    type: REDIS
  data:
    redis:
      port: 6379
      host: localhost
  security:
    user:
      name: ${SECURITY_CONFIG_USER_NAME}
      password: ${SECURITY_CONFIG_PASSWORD}

logging:
  level:
    root: info

server:
  port: 8085


resilience4j:
  circuitbreaker:
    instances:
      recipe:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  retry:
    instances:
      recipe:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    instances:
      recipe:
        timeoutDuration: 5s
        cancelRunningFuture: true


cache:
  ttl: 10

data-source:
  base-url: recipe

management:
  endpoint.health.show-details: always
  health.circuitbreakers.enabled: true